function applyImports() {}
function applyTemplates() {}
function attribute() {}
function attributeSet() {}
function callTemplate() {}
function choose() {}
function comment() {}
function copy() {}
function copyOf() {}
function decimalFormat() {}
function element() {}
function fallback() {}
function forEach() {}
function xsltIf() {}
function xsltImport() {}
function include() {}
function key() {}
function message() {}
function namespaceAlias() {}
function number() {}
function otherwise() {}
function output() {}
function param() {}
function preserveSpace() {}
function processingInstruction() {}
function sort() {}
function stripSpace() {}
function stylesheet() {}
function template() {}
function text() {}
function transform() {}
function valueOf() {}
function variable() {}
function when() {}
function withParam() {}
